### ISSUE TITLE
Is there a 64-bit version for Rance 4.x ?

### ISSUE THREAD

**Issue by silas1037** [kichikuou/system3-sdl2#10]
I want to create a translation for them.

**Comment by kichikuou** [comment]
You can download Windows build of latest revision from [here](https://github.com/kichikuou/system3-sdl2/actions/workflows/windows-msvc.yml).
Click the top item of the list and then select `system3-sdl2-64bit` to download the 64-bit version.

What language are you trying to translate into? System3-sdl2 currently supports only Shift JIS character encoding, so some code changes will be needed to support languages with characters not included in Shift JIS.

**Comment by silas1037** [comment]
> 单击列表的顶部，然后选择`system3-sdl2-64bit`下载64位版本。

Thanks, but I mean the Rance 4.1 & 4.2, which I could only find "Scenario Decoder SYSTEM3" powered by English translators and they are not of system3.5-4.x. I want to find the version which is supported by xsystem3-sdl2.

**Comment by kichikuou** [comment]
Rance 4.1/4.2 are based on System 3.0, which is not compatible with System 3.5-3.9. That means `xsystem35-sdl2` and `xsys35c` cannot be used, unfortunately.

Check out [RottenBlock’s list of System programming resources](https://alicesoft.fandom.com/wiki/User_blog:RottenBlock/System_Programming_Resources) for modding tools for System 3.0.

**Comment by silas1037** [comment]
Thanks, the tests of localization projects are passed.
