### ISSUE TITLE
Cannot load font file

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/system3-sdl2#11]
Since the change "Android: Allow specifying custom fonts in system3.ini," I haven't been able to load fonts via command arguments on Windows. Note that the game does still load the default font, because it uses open_resource() instead of SDL_RWFromFP(). When my code tries to use SDL_RWFromFP, it gives me the following error:

"Cannot load font file [x]: SDL not compiled with stdio support."

I can't find any helpful details about this error message online. Note that I'm using the default SDL.dll for my compiler, or at least I think I am. Downloading a fresh, default SDL.dll and SDL_ttf.dll doesn't change anything either. Am I making a simple mistake again?

**Comment by kichikuou** [comment]
Thanks! I was not aware that `SDL_RWFromFP` does not work on Windows, as [noted](https://wiki.libsdl.org/SDL_RWFromFP#remarks) in the Wiki. (In fact it works in MSYS2 build, and I had only tested with that.)
