### ISSUE TITLE
Config file error

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/system3-sdl2#12]
When trying to use the new config file system, I encountered a parser error. Thankfully, I was able to fix the error, but you should be the one to decide if it's the right fix. The fix is simple: in config.cpp, ln94, change "if (current_section == CONFIG)" to "else if". The code seemed to be checking the line that reads "[config]" and was producing an error when it didn't include any instructions on the same line.

Also, there's a typo in the Readme: at one point you say "ststem3.ini" instead of "system3.ini."

**Comment by kichikuou** [comment]
Fixed, thanks!
