### ISSUE TITLE
Redirect of pictures for Maria and Kanpan

### ISSUE THREAD

**Issue by silas1037** [kichikuou/system3-sdl2#13]
Hi! Aldexplorer2 doesnt seem to support png reimported into vsp CG pack of Maria and Kanpan. I am looking for a way without modifing source code of aldexplorer. Maybe system3-sdl2 could be modified to use outsude pictures. How to redirect fixed picture outside picture pack by filenames?

And new zh-translation of Rance IV has published with your xsystem35-sdl2's executable and it works well, thanks for your work!

**Comment by RottenBlock** [comment]
This shouldn't be necessary. Use ALDExplorer's File -> New empty archive file to create a second archive called BCG.DAT and store the images there, instead. The game will load all the image archives at once.

**Comment by silas1037** [comment]
> This shouldn't be necessary. Are you trying to load new images alongside the existing ones? Use ALDExplorer's "File -> New empty archive file" to create a second archive called BCG.DAT and store the images there, instead. The game will load both image archives at once.

Thx, but it will create system 3.0's DAT and it won't effects (Save As, NOT Save As Patch).
I try to merge *.vsp from original ACG and BCG to new ACG.dat without picture I will replace, and put my new picture to BCG.dat, it won't show BCG's things.
I try to merge new pitures' vsp and old vsp to one ACG.dat, but it call bugs. 

The pictures I wanna fix are cg_0021/43/44/45. I extracted them from DPS All, as I could not see anything from vsp of Super dps.

**Comment by RottenBlock** [comment]
If you can fix the images in DPS All, why not just work with DPS All?

**Comment by kichikuou** [comment]
Apparently Aldexplorer2 does not support the CG format used in the Super DPS version of Maria and Kanpan. The format is called `pms` in system3-sdl2 (decoder is [ags_pms.cpp](https://github.com/kichikuou/system3-sdl2/blob/master/src/sys/ags_pms.cpp)). You can use [AliceConv](https://github.com/Lutepatious/AliceConv) to extract them, where the format is called `VSP256`.

Older AliceSoft games use a wide variety of CG formats ([this comment](https://github.com/Lutepatious/AliceConv/blob/f00c8b78b9eba0bd01e02691045aa75770ad8f8d/VSPtoPNG/VSPtoPNG.c#L16-L29) in AliceConv is a good summary of them), and it's difficult to distinguish them from the file header.

System3-sdl2 simply switches the CG decoding function to use depending on the game ID. For example, [`load_pms` is used in Super DPS](https://github.com/kichikuou/system3-sdl2/blob/b64e8ed129d4abc959d3005cb5b5a7b53774b1fc/src/sys/ags_draw.cpp#L61-L63). This is why just adding vsp CGs extracted from DPS All will not work. Try modifying `AGS::load_cg()` if you want support multiple formats in a game.

I agree that it's easiest to work with DPS All from the beginning, if possible.

P.S. I have emailed you (at magsec2@...) about Rance4 Chinese version and xsystem35-sdl2. Have you read it?

**Comment by silas1037** [comment]
>I agree that it's easiest to work with DPS All from the beginning, if possible.
Ok, I would try.

>P.S. I have emailed you (at magsec2@...) about Rance4 Chinese version and xsystem35-sdl2. Have you read it?

Sorry, my miss. I have replied and will finish the imcomplete work soon.

**Comment by silas1037** [comment]
But now I only finished translation of Maria and Kanpan, even not considering other dps. If I could fix dps all to only show maria, that would be the best solution.

**Comment by kichikuou** [comment]
> If I could fix dps all to only show maria, that would be the best solution.

Yeah, that's the effort you have to make when you take that approach.

If you want to work with the Super DPS version as you planned originally, I just added old-PMS (VSP256) format support in xsys35c's `pms` command in kichikuou/xsys35c@ffea856. `pms --system2 *.vsp` will convert the CGs to PNG, and `pms -e --system2 *.png` will convert the PNGs back to the original format (but now with the extension `.pms`).

In any case, I would recommend that you learn some SystemX programming. Being able to do it would be very useful when working on other games too.

**Comment by silas1037** [comment]
Thanks,  it works well.

**Comment by kichikuou** [comment]
> You mean the system3.0 and 3.5's fuction?

Yes. For System 1-3, `System Command Manual.txt` in Sys0Decompiler is a good introductory document.

**Comment by kichikuou** [comment]
Let me close this, assuming the xsys35c update above resolved the issue.
