### ISSUE TITLE
Stable Release

### ISSUE THREAD

**Issue by silas1037** [kichikuou/system3-sdl2#19]
The MSYS built from Actions could not be run.
Well, how to get a stable and common-used one by actions building?

And, it cannot show savedata when loading on WinXP.

**Comment by kichikuou** [comment]
MSYS action does not create archive artifacts. Please use [Windows (MSVS) Build](https://github.com/kichikuou/system3-sdl2/actions/workflows/windows-msvc.yml) instead.

> And, it cannot show savedata when loading on WinXP.

Sorry, I don't have WinXP environment.

**Comment by kichikuou** [comment]
Released [Windows v0.7.0](https://github.com/kichikuou/system3-sdl2/releases/tag/windows-0.7.0).
