### ISSUE TITLE
Visual Studio - Multiple Platforms

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/system3-sdl2#20]
I'm not really familiar with mixing CMake with Visual Studio, so maybe you can help me with something. During the Configure step, CMake asks you to specify your platform: x64 or x86. I'd like to have both in the same project, as is standard for Visual Studio, but can't figure out how to do it. Is there a way to get CMake to generate for both platforms? Is there a way to adjust CMake's solution to support both? Normally that wouldn't be hard but I'm getting some odd errors when I try. Or, failing all else, should I just generate separate projects?

**Comment by kichikuou** [comment]
Unfortunately, CMake cannot generate multiple-architecture Visual Studio projects. You have to use separate projects.
https://gitlab.kitware.com/cmake/cmake/-/issues/18450
