### ISSUE TITLE
Uninitialized text_font_maxsize leading to minor errors

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/system3-sdl2#25]
You were right, that problem we were talking about was uninitialized memory, which was why I was only having the problem some of the time. Specifically, the problem was in the AGS variable text_font_maxsize. Setting text_font_maxsize to 0 during the AGS constructor solves the problem. Obviously it's not a very frequent problem but it's a simple and reliable fix.

**Comment by kichikuou** [comment]
Fixed, thanks!
