### ISSUE TITLE
main program crash

### ISSUE THREAD

**Issue by silas1037** [kichikuou/system3-sdl2#27]
Hi! I add text below to system3.ini and fail to open program. Well, I want to define different.

[string]
back        = 戻る
next_page   = 次のページ
dps_custom  = カスタム
dps_linus   = リーナス
dps_katsumi = かつみ
dps_yumiko  = 由美子
dps_itsumi  = いつみ
dps_hitomi  = ひとみ
dps_mariko  = 真理子

**Comment by silas1037** [comment]
reason: no brank line permitt.

https://github.com/kichikuou/system3-sdl2/blob/a6538e32d7083b10129050286ea8ecbf495ddb66/src/config.cpp#L195

**Comment by silas1037** [comment]
BTW, how to disable converting full-width char to half-width?

**Comment by kichikuou** [comment]
Thanks for reporting, I'll fix it.

For full-width/half-width conversion, you can switch between the two modes with ADV commands, not with the config file.

- system3-sdl2 has two modes, full-width mode and half-width mode, and the default is full-width mode.
- In the full-width mode, half-width characters are converted to full-width characters.
- In the half-width mode, full-width characters are converted to half-width characters.

System 1 and 3 can switch the modes with `Y 240` command.
`Y 240, 1:` switches to the half-width mode, and `Y 240, 0:` switches to the full-width mode.

This is the current situation, but let me know if there is a problem with your use case.
