### ISSUE TITLE
config to_bool always returns true?

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/system3-sdl2#28]
I was trying out the new, English release of Policewoman VX, and noticed that it wasn't using antialiasing. I checked the config.ini file and everything seemed fine, "noantialiasing" was set to "false" as intended, and so went into the debugger and found that to_bool's strcasecmp and strcmp functions were always returning true, even when you send them the string "false." 

The config file itself doesn't seem to matter, I could even change the variable in code and it would still declare a match for every one of strcasecmp(s, "yes"), strcasecmp(s, "true"), strcasecmp(s, "on") and strcmp(s, "1"). Even checking to see if they were all true simultaneously would pass:

`strcasecmp(s, "yes") && strcasecmp(s, "true") && strcasecmp(s, "on") && strcmp(s, "1")`

Is it just me? If so, what on earth have I done?

**Comment by kichikuou** [comment]
Fixed in v1.0.2.

**Comment by RottenBlock** [comment]
Thanks a lot!
