### ISSUE TITLE
rance4/toushin hint discs

### ISSUE THREAD

**Issue by alan-zxs** [kichikuou/system3-sdl2#32]
ランスIV オプションディスク/Rance 4 Option Disc
https://vndb.org/v32938
This game is not on your list, but it works with system3-sdl2 (I used rance42 as the game_id).
The issue is that if you add a .ttf font in the system3.ini file, the game crashes.

ランス外伝 －闘神都市－/Toushin Toshi Hint Disk
https://vndb.org/v29954
There are also problems with the music.
Try to enable `fm = true` in the system3.ini file.

**Comment by kichikuou** [comment]
> ランスIV オプションディスク/Rance 4 Option Disc
> https://vndb.org/v32938
> This game is not on your list, but it works with system3-sdl2 (I used rance42 as the game_id).

Really? I get this error with `-game rance42`:
![rance4opt](https://github.com/user-attachments/assets/46eca997-c446-470b-885e-2dc02b7abe9a)

> ランス外伝 －闘神都市－/Toushin Toshi Hint Disk
> https://vndb.org/v29954
> There are also problems with the music.
> Try to enable `fm = true` in the system3.ini file.

This game is not supported. I meant to imply that by "闘神ランス does not work" in the list. I'll correct the title on the list.

**Comment by kichikuou** [comment]
> It won't work if the .ini file contains the `fontfile` parameter (crash on startup)

It is probably a problem dependent on the font file, not the game. What font file did you use? With other fonts do you get the same error?

> You can bypass this error for the Rance 4 Option Disc by using the `ayumi_fd` identifier. However, you will get stuck at the next screen. Perhaps this information will be useful.

Rance 4 Option Disc is a System2 game. It does not work because of unimplemented commands, like ALICEの館II (#30). There are currently no plans to add support for them.

**Comment by kichikuou** [comment]
Link removed. Please do not post copyrighted font file.

**Comment by kichikuou** [comment]
Fixed both issues in Hashiri Onna II. You can download windows build [here](https://github.com/kichikuou/system3-sdl2/actions/runs/12272055201).
