### ISSUE TITLE
Porting Menu Features

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/system3-sdl2#4]
Hi again. I've been working on English support for system3-sdl2, and I'm nearly ready with the Windows release, but I thought of something else I wanted to discuss with you. In the original system3 for win32, the program had a menu bar. Obviously, menu bars are system-dependent and that's not portable, but the menu included a handful of features that system3-sdl2 could easily support, if only it had a way to turn them back on. Can you think of anything we could do that might restore these features? I've been considering a few alternatives, like desktop-exclusive use of the F-keys, but maybe you can think of something portable.

Reminder of the features I'm talking about:

- Resetting the game - I use this one a lot and it's the one I miss the most. While the code for this is no longer in system3-sdl, it could be copy and pasted without trouble.
- Fullscreen support - Looks hideously stretched, I'm personally not a fan. But some desktop users might want it? SDL should make this easy enough to implement.
- Sound source toggle - Toggles between FM and CD sound in games that support it. system3-sdl2 still has all the code required just waiting to be used.
- Message wait mode - Produces a teletype effect when printing text. The code is still around waiting to be used.

The menu also supported quitting the game and served as an alternate way to use the Skip Text feature, but those aren't really required.

Hope to hear from you, maybe you'll have some ideas!

**Comment by kichikuou** [comment]
Hi, glad to hear that the English support is nearing completion!

I think it is better to implement the menu as platform-specific code, for example using Win32 API on Windows. Another option is to implement it on our own using SDL's rendering API, but that would need a fair amount of code and one implementation may not fit all platforms (desktop, phone, browser) well.

Actually restoring menu support for Windows was pretty easy. Here's my work-in-progress code: https://github.com/kichikuou/system3-sdl2/pull/5

The reset feature needs some more work. The TOTO's implementation [simply deleted `nact` and recreated it](https://github.com/kichikuou/system3-sdl2/blob/TOTO-original/src/winmain.cpp#L300-L305), but in system3-sdl2 we can't do the same because the message pump is implemented inside a `NACT`'s method.

I'm going to merge it into `master` once I finish implementing the reset feature.

**Comment by kichikuou** [comment]
And now reset works :)

The code is merged into the `master` branch. Implementation in other platforms will be done later.

**Comment by RottenBlock** [comment]
You do quick work!

One thing I'm noticing with the menu engaged is that it isn't added to the window's vertical height, and the game ends up squashed. Adding another 20px to the window's height will fix that, but obviously we want the extra height to be exclusive to Win32 for the time being. Other than that, it seems perfect!

**Comment by kichikuou** [comment]
Ah good point, I was wondering why I see black vertical bars at the sides of the window.

It should be fixed by commit 932df7e.

**Comment by RottenBlock** [comment]
That's got it. I think that wraps this up, thanks again!

**Comment by RottenBlock** [comment]
Came across a problem with this and possibly other parts of the music-switching code. It's not your fault, the problem also seems to exist in the the original system3 for win32. If you switch from FM Music to CD Music using the menu, all CD music will play the wrong track from this point forward, offset by -1. For example:

1. Go to the Rance 4.1's Alice's Mansion and try the sound test. Select the option to play all the tracks in order.
2. Track 1 of 17 plays and its info is displayed.
3. Using the top menu, press Sound -> FM Sound. The  FM version of Track 1 plays correctly.
4. Using the top menu, press Sound -> CD Music. The CD version of Track 17 begins to play!
5. Click to advance to the next track. The game is supposed to play Track 2, but begins to play Track 1, instead.
6. The problem persists for the rest of the sound test: Track 3 plays Track 2, Track 4 plays Track 3, etc.
7. Switching to FM Sound a second time plays the proper track, but returning to CD Music will once again get you the wrong track, offset by 1. Note that the problem doesn't get worse: we don't start playing offset by -2 or -3, always -1.

Because this is Rance 4.1, it's worth noting that the in-game sound source menu works just fine using Z 101, 102, etc, though obviously that's not the smoothest way to do things on the executable side.

That about covers it, I think!

**Comment by kichikuou** [comment]
This is a complex issue that deserves an independent issue. Let's discuss in #6.
