### ISSUE TITLE
Music switching from menubar is buggy

### ISSUE THREAD

**Issue by kichikuou** [kichikuou/system3-sdl2#6]
Moved from https://github.com/kichikuou/system3-sdl2/issues/4#issuecomment-714922273.

In System3, `Z 1xx` command defines a mapping from music number to track number of the CD. For example, `Z 101, 2` specifies that track 2 should be played for music number 1. If this mapping is not specified or track 0 is specified, MIDI sound is used.

In some games (e.g. Rance 4.1 and 4.2), CD/FM sound can be switched from in-game menu. Selecting "FM" (which means MIDI to us) clears the mapping with zero, and selecting "CD" re-populates the mapping.

Some other games (e.g. Only You) lets the user choose a sound device at the start of the game. If "FM" is chosen, the `Z 1xx` command is not executed at all.

In `system3-sdl2` code, this mapping is stored in the [`MAKO::cd_track[]`](https://github.com/kichikuou/system3-sdl2/blob/4c5ee00/src/sys/mako.h#L42) array. In the current implementation, selecting "FM Sound" from the menubar clears this array, and selecting "CD Audio" [sets](https://github.com/kichikuou/system3-sdl2/blob/4c5ee00/src/sys/nact.cpp#L430) `cd_track [i] = i` for 1 <= i <= 99.

There's a bug here. In Rance 4.1, the correct mapping is `cd_track[i] = i + 1`. This is the reason why selecting "CD Audio" plays a track that is off by one. Note that `cd_track[i] = i` is correct in some other games (e.g. Only You), and some others have more random mappings (e.g. D.P.S. ALL).

If the `Z 1xx` command has been executed in the past, the mapping can be restored when "CD Audio" menu is selected. That should fix Rance 4.x, because Rance 4.x always issue `Z 1xx` commands at the startup. But in other games, it's not guaranteed that the correct mapping is known when "CD Audio" menu is selected.

**Comment by kichikuou** [comment]
The usefulness of this feature is a bit questionable to me. In System3 for Win32, which used a real CD device, there was certainly a trade-off between CD and MIDI; CD has better sound quality, but you have to put the disc in the drive / seek time is long.

However, with System3-sdl2, which uses CD emulation with mp3, isn't CD always better? Why would a user want to switch to MIDI when CD is available?

**Comment by RottenBlock** [comment]
There are always people who want to play the original version, even if the disparity between FM chips, sound cards, and modern MIDI implementation makes the relationship with the "original" questionable. I'm sure one get a few downloads if they offered alternate sound packs for Alicesoft games using MP3 recordings off original hardware, but that's neither here nor there.  I think the feature's worth keeping.

That said, the mess Alicesoft has left us is hard to fix. Is the problem simply that Z 1xx commands aren't used in certain startups, or do games like DPS All change the CD music as the game plays, in a way we can't overcome?  I've seen some of DPS All's code, I know it's pretty unorthodox.

If it's just a matter of the game not providing the order up front, could we append the -playlist file to give a default starting order, and allow that order to be modified by subsequent Z 1xx commands?

**Comment by kichikuou** [comment]
Fair enough, let's not remove the feature. :-)

> Is the problem simply that Z 1xx commands aren't used in certain startups, or do games like DPS All change the CD music as the game plays, in a way we can't overcome?

As far as I can tell, every game (including D.P.S. ALL) seemed to have a fixed mapping. Assuming that's true for all games, probably the simplest solution is to have a copy of those mappings in the code and use CRC32 to select from it.

**Comment by kichikuou** [comment]
The code is in, although I've only tested it with a few games.

If you find other games that require non-default mappings, or if you can confirm that some game works with the default mapping, please let me know.

**Comment by RottenBlock** [comment]
Sounds like a plan, I'll implement it on my end!
