### ISSUE TITLE
Application Error - 0xc000007b

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/system3-sdl2#7]
Hi again. Recently, I got some error reports for the beta version of the English port saying that the program wouldn't run on Windows due to Application Error 0xc000007b. Looking into the problem, I discovered that while I can run my the English version just fine, I suddenly can't run your original, Japanese version without getting the same error. This certainly didn't used to be the case. I really feel that I'm missing something obvious but I don't want to make any leading suggestions.

Here's what I can tell you:

- Compiled using your relatively recent code and most recent instructions. Debug build, although the other users were encountering the problem in my Release build.
- In my case, running on Windows 10 64bit in English mode. Problem occurs in both command line and explorer.
- SDL2.dll, SDL2_mixer.dll, SDL2_ttf.dll, libfreetype-6.dll, and zlib1.dll are present in the folder.
- Little Vampire data files used for testing, though since the program crashes instantly I don't think that matters.
- While I haven't tested this on your Japanese version yet, in my version it didn't seem to matter if the code was compiled for 64 bit or 32 bit.

Any ideas?

**Comment by kichikuou** [comment]
It seems 32-bit and 64-bit DLLs are mixed in your archive.

Here's what I get when running MSYS2's `file` command in `Little Vampire (Patch 1.5 Hotfix)/game` directory:
```
$ file *.exe *.dll
system3-sdl2.exe:  PE32 executable (GUI) Intel 80386 (stripped to external PDB), for MS Windows
libfreetype-6.dll: PE32+ executable (DLL) (console) x86-64 (stripped to external PDB), for MS Windows
SDL2.dll:          PE32 executable (DLL) (console) Intel 80386 (stripped to external PDB), for MS Windows
SDL2_mixer.dll:    PE32 executable (DLL) (GUI) Intel 80386 (stripped to external PDB), for MS Windows
SDL2_ttf.dll:      PE32 executable (DLL) (GUI) Intel 80386 (stripped to external PDB), for MS Windows
zlib1.dll:         PE32+ executable (DLL) (console) x86-64 (stripped to external PDB), for MS Windows
```

Please make sure that you distribute DLLs for the same architecture as the exe.

**Comment by RottenBlock** [comment]
Ah, of course, I knew it would be something stupid. I must have opened the wrong directory by mistake when adding those dlls to the hotfix. Sorry about the trouble.

You can close this, though I'm afraid I may be back in a few days with an emscripten problem. For now I'm going to try a few more things.

Thanks for your time!

**Comment by kichikuou** [comment]
Closing. Please create a new issue if you need anything else :)
